<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">

        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h4 class="content-header-title float-left mb-0">
                            <a href="https://verdum.com/pedidos/perfiles/index"><strong><i class="fa-solid fa-caret-left fa-beat"></i> Regresar</strong></a>                                                        
                        </h4>
                    </div>
                </div>
            </div>
        </div>


        <div class="content-body">
            <section id="basic-horizontal-layouts">
                <div class="row">
                    <div class="col-md-8 col-12">
                        <div class="card">
                            <div class="card-header border-bottom p-1">
                                <div class="head-label">
                                    <h6 class="mb-0"></h6>
                                </div>
                                <div class="dt-action-buttons text-left">
                                    <div class="dt-buttons d-inline-flex">
                                        <button id="btnagregar" name="<?php echo $this->perfil ?>" type="button" class="dt-button create-new btn btn-primary"><i class="fa-solid fa-pen-to-square"></i>&nbsp; AGREGAR ACCESO </button>
                                    </div>
                                </div>
                            </div>

                            <div class="card-header">
                                <h4 class="card-title"> <i class="fa-solid fa-list"></i></i> Lista de Menu</h4>
                            </div>

                            <div class="col-md-12 col-12">
                                <table id="example1" class="table table-sm table-hover">
                                    <thead class="thead-light">
                                        <tr class="text-center">
                                            <th># Código</th>
                                            <th>Nombre</th>
                                            <th>#</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (isset($this->menu)) { ?>
                                            <?php foreach ($this->menu as $tr) { ?>
                                                <tr>
                                                    <td class="text-center"><?php echo $tr['i_submenu'] ?></td>
                                                    <td class="text-left"><?php echo $tr['v_menu'] ?></td>
                                                    <td class='text-center'>
                                                        <a <?php if ($tr['v_menu'] == "Nosotros") {
                                                                echo "style='display:none'";
                                                            } else {
                                                                echo "style='display:inline-block'";
                                                            } ?> id='<?php echo $tr['i_submenu'] ?>' perfil='<?php echo $tr['i_perfil'] ?>' class='btn btn-danger btn-sm text-white deletemenu'>
                                                            <i class='fa fa-trash-alt'></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            <?php } ?>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>

                    <div class="col-md-4 col-12">
                        <div class="card">
                            <div class="card-header border-bottom p-1">
                                <div class="head-label">
                                    <h6 class="mb-0"></h6>
                                </div>
                                <div class="dt-action-buttons text-left">
                                    <div class="dt-buttons d-inline-flex">
                                         <br>
                                         <br>
                                        
                                    </div>
                                </div>
                            </div>

                            <div class="card-header">
                                <h4 class="card-title"> <i class="fa-solid fa-list"></i></i> Lista de SubMenu</h4>
                            </div>

                            <div class="col-md-12 col-12">
                                <table id="example2" class="table table-sm table-hover">
                                    <thead class="thead-light">
                                        <tr class="text-center">
                                            <th># Código</th>
                                            <th>Menú</th>
                                            <th>Nombre</th>
                                            <th>#</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (isset($this->submenu)) { ?>
                                            <?php foreach ($this->submenu as $tr) { ?>
                                                <tr>
                                                    <td class="text-center"><?php echo $tr['i_submenu'] ?></td>
                                                    <td class="text-center"><?php echo $tr['v_menu'] ?></td>
                                                    <td class="text-left"><?php echo $tr['v_submenu'] ?></td>
                                                    <td class='text-center'>
                                                        <a id='<?php echo $tr['i_submenu'] ?>' menu="<?php echo $tr['i_menu'] ?>" perfil='<?php echo $tr['i_perfil'] ?>' class='btn btn-danger btn-sm text-white delete'>
                                                            <i class='fa fa-trash-alt'></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            <?php } ?>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

<!-- MODAL AGREGAR ACCESO DATO-->
<div class="modal fade" id="modal-editar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">AGREGAR ACCESOS:&nbsp;</h5><b><?php echo $this->perfil ?></b>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Menú:</label>
                        <select id="menu" tabindex="1" class="select2 form-control form-control-lg">
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Sub Menú:</label>
                        <select id="submenu" tabindex="2" class="select2 form-control form-control-lg">
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="btnguardar" type="button" class="btn btn-success btn-block">
                                <i class="fas fa-save"></i>
                                <b>Guardar</b></button>
                        </div>
                        <br>
                        <br>
                        <div class="col-sm-6">
                            <button id="btncancelar" type="button" class="btn btn-danger btn-block">
                                <i class="fas fa-ban"></i>
                                <b>Cancelar</b></button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>