<div id="support-trackers-chart" style="min-height: 194.875px;">
    <div id="apexchartsmgaedyia" class="apexcharts-canvas apexchartsmgaedyia apexcharts-theme-light" style="width: 300px; height: 194.875px;"><svg id="SvgjsSvg1006" width="300" height="194.875" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" class="apexcharts-svg" xmlns:data="ApexChartsNS" transform="translate(0, 0)" style="background: transparent;">
            <g id="SvgjsG1008" class="apexcharts-inner apexcharts-graphical" transform="translate(63, 20)">
                <defs id="SvgjsDefs1007">
                    <clipPath id="gridRectMaskmgaedyia">
                        <rect id="SvgjsRect1010" width="182" height="200" x="-3" y="-1" rx="0" ry="0" opacity="1" stroke-width="0" stroke="none" stroke-dasharray="0" fill="#fff"></rect>
                    </clipPath>
                    <clipPath id="gridRectMarkerMaskmgaedyia">
                        <rect id="SvgjsRect1011" width="180" height="202" x="-2" y="-2" rx="0" ry="0" opacity="1" stroke-width="0" stroke="none" stroke-dasharray="0" fill="#fff"></rect>
                    </clipPath>
                    <linearGradient id="SvgjsLinearGradient1016" x1="0" y1="1" x2="1" y2="1">
                        <stop id="SvgjsStop1017" stop-opacity="1" stop-color="rgba(115,103,240,1)" offset="0"></stop>
                        <stop id="SvgjsStop1018" stop-opacity="1" stop-color="rgba(255,255,255,1)" offset="1"></stop>
                        <stop id="SvgjsStop1019" stop-opacity="1" stop-color="rgba(255,255,255,1)" offset="1"></stop>
                    </linearGradient>
                    <linearGradient id="SvgjsLinearGradient1027" x1="0" y1="1" x2="1" y2="1">
                        <stop id="SvgjsStop1028" stop-opacity="1" stop-color="rgba(115,103,240,1)" offset="0"></stop>
                        <stop id="SvgjsStop1029" stop-opacity="1" stop-color="rgba(234,84,85,1)" offset="1"></stop>
                        <stop id="SvgjsStop1030" stop-opacity="1" stop-color="rgba(234,84,85,1)" offset="1"></stop>
                    </linearGradient>
                </defs>
                <g id="SvgjsG1012" class="apexcharts-radialbar">
                    <g id="SvgjsG1013">
                        <g id="SvgjsG1014" class="apexcharts-tracks">
                            <g id="SvgjsG1015" class="apexcharts-radialbar-track apexcharts-track" rel="1">
                                <path id="apexcharts-radialbarTrack-0" d="M 53.346646341463384 159.0213691892382 A 69.30670731707318 69.30670731707318 0 1 1 122.65335365853659 159.02136918923821" fill="none" fill-opacity="1" stroke="rgba(255,255,255,0.85)" stroke-opacity="1" stroke-linecap="butt" stroke-width="10.852439024390247" stroke-dasharray="0" class="apexcharts-radialbar-area" data:pathOrig="M 53.346646341463384 159.0213691892382 A 69.30670731707318 69.30670731707318 0 1 1 122.65335365853659 159.02136918923821"></path>
                            </g>
                        </g>
                        <g id="SvgjsG1021">
                            <g id="SvgjsG1026" class="apexcharts-series apexcharts-radial-series" seriesName="Avance" rel="1" data:realIndex="0">
                                <path id="SvgjsPath1031" d="M 53.346646341463384 159.0213691892382 A 69.30670731707318 69.30670731707318 0 0 1 53.346646341463426 38.97863081076179" fill="none" fill-opacity="0.85" stroke="url(#SvgjsLinearGradient1027)" stroke-opacity="1" stroke-linecap="butt" stroke-width="10.852439024390247" stroke-dasharray="8" class="apexcharts-radialbar-area apexcharts-radialbar-slice-0" data:angle="120" data:value="40" index="0" j="0" data:pathOrig="M 53.346646341463384 159.0213691892382 A 69.30670731707318 69.30670731707318 0 0 1 53.346646341463426 38.97863081076179"></path>
                            </g>
                            <circle id="SvgjsCircle1022" r="58.88048780487805" cx="88" cy="99" class="apexcharts-radialbar-hollow" fill="transparent"></circle>
                            <g id="SvgjsG1023" class="apexcharts-datalabels-group" transform="translate(0, 0) scale(1)" style="opacity: 1;"><text id="SvgjsText1024" font-family="Helvetica, Arial, sans-serif" x="88" y="94" text-anchor="middle" dominant-baseline="auto" font-size="1rem" font-weight="400" fill="#5e5873" class="apexcharts-text apexcharts-datalabel-label" style="font-family: Helvetica, Arial, sans-serif;">Avance</text><text id="SvgjsText1025" font-family="Helvetica, Arial, sans-serif" x="88" y="130" text-anchor="middle" dominant-baseline="auto" font-size="1.714rem" font-weight="400" fill="#5e5873" class="apexcharts-text apexcharts-datalabel-value" style="font-family: Helvetica, Arial, sans-serif;">40%</text></g>
                        </g>
                    </g>
                </g>
                <line id="SvgjsLine1032" x1="0" y1="0" x2="176" y2="0" stroke="#b6b6b6" stroke-dasharray="0" stroke-width="1" class="apexcharts-ycrosshairs"></line>
                <line id="SvgjsLine1033" x1="0" y1="0" x2="176" y2="0" stroke-dasharray="0" stroke-width="0" class="apexcharts-ycrosshairs-hidden"></line>
            </g>
            <g id="SvgjsG1009" class="apexcharts-annotations"></g>
        </svg>
        <div class="apexcharts-legend"></div>
    </div>
</div>