<div id="support-trackers-chart" style="min-height: 194.875px;">
    <div id="apexchartsuaf0bmvsf" class="apexcharts-canvas apexchartsuaf0bmvsf apexcharts-theme-light" style="width: 300px; height: 194.875px;"><svg id="SvgjsSvg1090" width="300" height="194.875" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" class="apexcharts-svg" xmlns:data="ApexChartsNS" transform="translate(0, 0)" style="background: transparent;">
            <g id="SvgjsG1092" class="apexcharts-inner apexcharts-graphical" transform="translate(63, 20)">
                <defs id="SvgjsDefs1091">
                    <clipPath id="gridRectMaskuaf0bmvsf">
                        <rect id="SvgjsRect1094" width="182" height="200" x="-3" y="-1" rx="0" ry="0" opacity="1" stroke-width="0" stroke="none" stroke-dasharray="0" fill="#fff"></rect>
                    </clipPath>
                    <clipPath id="gridRectMarkerMaskuaf0bmvsf">
                        <rect id="SvgjsRect1095" width="180" height="202" x="-2" y="-2" rx="0" ry="0" opacity="1" stroke-width="0" stroke="none" stroke-dasharray="0" fill="#fff"></rect>
                    </clipPath>
                    <linearGradient id="SvgjsLinearGradient1100" x1="0" y1="1" x2="1" y2="1">
                        <stop id="SvgjsStop1101" stop-opacity="1" stop-color="rgba(115,103,240,1)" offset="0"></stop>
                        <stop id="SvgjsStop1102" stop-opacity="1" stop-color="rgba(255,255,255,1)" offset="1"></stop>
                        <stop id="SvgjsStop1103" stop-opacity="1" stop-color="rgba(255,255,255,1)" offset="1"></stop>
                    </linearGradient>
                    <linearGradient id="SvgjsLinearGradient1111" x1="0" y1="1" x2="1" y2="1">
                        <stop id="SvgjsStop1112" stop-opacity="1" stop-color="rgba(115,103,240,1)" offset="0"></stop>
                        <stop id="SvgjsStop1113" stop-opacity="1" stop-color="rgba(234,84,85,1)" offset="1"></stop>
                        <stop id="SvgjsStop1114" stop-opacity="1" stop-color="rgba(234,84,85,1)" offset="1"></stop>
                    </linearGradient>
                </defs>
                <g id="SvgjsG1096" class="apexcharts-radialbar">
                    <g id="SvgjsG1097">
                        <g id="SvgjsG1098" class="apexcharts-tracks">
                            <g id="SvgjsG1099" class="apexcharts-radialbar-track apexcharts-track" rel="1">
                                <path id="apexcharts-radialbarTrack-0" d="M 53.346646341463384 159.0213691892382 A 69.30670731707318 69.30670731707318 0 1 1 122.65335365853659 159.02136918923821" fill="none" fill-opacity="1" stroke="rgba(255,255,255,0.85)" stroke-opacity="1" stroke-linecap="butt" stroke-width="10.852439024390247" stroke-dasharray="0" class="apexcharts-radialbar-area" data:pathOrig="M 53.346646341463384 159.0213691892382 A 69.30670731707318 69.30670731707318 0 1 1 122.65335365853659 159.02136918923821"></path>
                            </g>
                        </g>
                        <g id="SvgjsG1105">
                            <g id="SvgjsG1110" class="apexcharts-series apexcharts-radial-series" seriesName="Avance" rel="1" data:realIndex="0">
                                <path id="SvgjsPath1115" d="M 53.346646341463384 159.0213691892382 A 69.30670731707318 69.30670731707318 0 0 1 18.693292682926824 98.99999999999999" fill="none" fill-opacity="0.85" stroke="url(#SvgjsLinearGradient1111)" stroke-opacity="1" stroke-linecap="butt" stroke-width="10.852439024390247" stroke-dasharray="8" class="apexcharts-radialbar-area apexcharts-radialbar-slice-0" data:angle="60" data:value="20" index="0" j="0" data:pathOrig="M 53.346646341463384 159.0213691892382 A 69.30670731707318 69.30670731707318 0 0 1 18.693292682926824 98.99999999999999"></path>
                            </g>
                            <circle id="SvgjsCircle1106" r="58.88048780487805" cx="88" cy="99" class="apexcharts-radialbar-hollow" fill="transparent"></circle>
                            <g id="SvgjsG1107" class="apexcharts-datalabels-group" transform="translate(0, 0) scale(1)" style="opacity: 1;"><text id="SvgjsText1108" font-family="Helvetica, Arial, sans-serif" x="88" y="94" text-anchor="middle" dominant-baseline="auto" font-size="1rem" font-weight="400" fill="#5e5873" class="apexcharts-text apexcharts-datalabel-label" style="font-family: Helvetica, Arial, sans-serif;">Avance</text><text id="SvgjsText1109" font-family="Helvetica, Arial, sans-serif" x="88" y="130" text-anchor="middle" dominant-baseline="auto" font-size="1.714rem" font-weight="400" fill="#5e5873" class="apexcharts-text apexcharts-datalabel-value" style="font-family: Helvetica, Arial, sans-serif;">20%</text></g>
                        </g>
                    </g>
                </g>
                <line id="SvgjsLine1116" x1="0" y1="0" x2="176" y2="0" stroke="#b6b6b6" stroke-dasharray="0" stroke-width="1" class="apexcharts-ycrosshairs"></line>
                <line id="SvgjsLine1117" x1="0" y1="0" x2="176" y2="0" stroke-dasharray="0" stroke-width="0" class="apexcharts-ycrosshairs-hidden"></line>
            </g>
            <g id="SvgjsG1093" class="apexcharts-annotations"></g>
        </svg>
        <div class="apexcharts-legend"></div>
    </div>
</div>