<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-body">
            <section id="dashboard-analytics">
                <div class="row" id="table-small">
                    <div class="col-md-12 col-12">
                        <div class="card">
                            <div class="card-header border-bottom p-1">
                                <div class="head-label">
                                    <h6 class="mb-0"></h6>
                                </div>
                                <div class="dt-action-buttons text-right">
                                    <div class="dt-buttons d-inline-flex">
                                        <button id="btnagregar" name="<?php echo $this->ConsultaTopePedido[0]['f_valortope_condicion_uno'] ?>" type="button" class="dt-button create-new btn btn-primary"><i class="fa-solid fa-cart-plus fa-beat"></i>&nbsp; NUEVO PEDIDO </button>
                                    </div>
                                </div>
                            </div>




                            <div class="card-header">
                                <h4 class="card-title"> <i class="fa-solid fa-list"></i></i> Lista de Pedidos para Compra</h4>
                            </div>

                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="tbpedidos" class="table table-sm table-hover">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th>#NroPedido</th>
                                                <th>Descripcion</th>
                                                <th>Tipo</th>
                                                <th>Solicita</th>
                                                <th>Realizado por:</th>
                                                <th>Moneda</th>
                                                <th>Fecha</th>
                                                <th>Estado</th>
                                                <th>Total</th>
                                                <th>Observado</th>
                                                <th>InfoSolomon</th>
                                                <th>Avance</th>
                                                <th class='text-center'>Imprimir</th>
                                                <th>Revisar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->ListadoPedidosUsuario)) { ?>
                                                <?php foreach ($this->ListadoPedidosUsuario as $pd) { ?>
                                                    <tr>
                                                        <td class="text-left">
                                                            <div class="media">
                                                                <div class="avatar bg-light-success mr-0">
                                                                    <div class="avatar-content">
                                                                        <i data-feather="shopping-cart" stroke-width="3" class="avatar-icon"></i>
                                                                    </div>
                                                                </div>
                                                                <div class="media-body my-auto">
                                                                    <h5 class="font-weight-bolder mb-0"><?php echo $pd['nu_correla'] ?></h5>
                                                                </div>
                                                            </div>
                                                        </td>

                                                        <td class="text-left"><strong><?php echo $pd['v_nombrepedido'] ?></strong> </td>
                                                        <td class="text-left"><?php echo $pd['v_tipo_pedido'] ?> </td>
                                                        <td class="text-left"><?php echo $pd['v_nombrearea'] ?> </td>
                                                        <td class="text-left"><?php echo $pd['v_nombreusuario'] ?></td>
                                                        <td class="text-left"><?php echo $pd['v_moneda'] ?></td>
                                                        <td class="text-left"><?php echo $pd['d_fecha'] ?></td>

                                                        <td class="text-left">
                                                            <div class="badge badge-light-<?php echo $pd['v_color_porcentaje'] ?>"><?php echo $pd['v_estado'] ?></div>
                                                        </td>

                                                        <td class="text-left"><?php echo $pd['nu_total'] ?></td>


                                                        <td class="text-center"><a id='<?php echo $pd['v_observacion'] ?>' class='<?php echo $pd['v_btn_observacion'] ?>'><span class='<?php echo $pd['v_span_observacion'] ?>'><b></b></span></a></td>
                                                        <td class="text-left"><strong><?php echo $pd['v_info_solomon'] ?></strong></td>
                                                        <td class='text-left'>
                                                            <span class="badge badge-glow badge-<?php echo $pd['v_color_porcentaje'] ?> "><?php echo $pd['f_porcentaje'] ?>%</span>
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trending-up text-success font-medium-2">
                                                                <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline>
                                                                <polyline points="17 6 23 6 23 12"></polyline>
                                                            </svg>
                                                        </td>

                                                        <td class='text-center'>
                                                            <a href="<?php echo BASE_URL ?>aprobarpedido/documentopedido/<?php echo  $pd['nu_correla'] ?>" class="btn btn-danger btn-sm bol" target="_blank" style="color:white"><i class="fas fa-file-pdf fa-beat"></i></a>
                                                        </td>

                                                        <td class='text-left'>
                                                            <a id='<?php echo $pd['nu_correla'] ?>' <?php $variable1 =  $pd['nu_correla'] ?> href="<?php echo BASE_URL ?><?php echo $pd['v_url'] ?>=<?php echo urlencode($variable1) ?>" class="btn btn-<?php echo $pd['v_btn1'] ?>"><i class="fas solid fa-<?php echo $pd['v_btn1Imagen'] ?>"></i></a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>



<div class="modal fade text-left" id="modal-observacion" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="myModalLabel160" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-gradient-primary">
                <h5 style="color:rgb(255,255,255)" class="modal-title"><i class="fa-solid fa-square-check"></i> NOTA DE OBSERVACION </h5>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        <label style="color:rgb(255,165,0)" class="form-label font-weight-bolder">Observacion</label>
                        <div class="input-group input-group-merge">
                            <div class=" input-group-prepend">
                                <span class="input-group-text"><i data-feather='folder-plus'></i></span>
                            </div>
                            <textarea class="form-control" rows="3" placeholder="Ingrese descripcion" readonly="readonly" id="notadescripcion"></textarea>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <!-- <button id="btnguardaretorno" type="button" class="btn btn-success btn-block waves-effect waves-float waves-light"><b>Retornar</b></button> -->
                        </div>
                        <div class="col-sm-6">
                            <button id="btncancelaretorno" type="button" class="btn btn-danger btn-block waves-effect waves-float waves-light"><b>Cancelar</b></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>