<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <!-- <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div> -->



        <div class="content-body">

            <section id="dashboard-analytics">

                <!-- <div class="card card-gray">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-chart-pie"></i>
                            &nbsp;<strong>DATOS</strong>
                        </h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <figure class="highcharts-figure">
                                    <div id="container1"></div>
                                </figure>
                            </div>
                        </div>
                    </div>
                </div> -->




                <div class="row" id="table-small">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title"> <i class="fas fa-chart-pie"></i> Pedidos de Compra</h4>
                            </div> 

                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="example2" class="table table-sm">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th>Project</th>
                                                <th>Client</th>
                                                <th>Users</th>
                                                <th>Status</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>



                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </section>


        </div>




    </div>
</div>
<!-- END: Content-->


<!--
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
        </div>


        <div class="content-body" style="color:rgb(248, 248, 248);">
            <section class="col-lg-6 connectedSortable">

                <div class="card card-gray">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-chart-pie"></i>
                            &nbsp;<strong>Ausentismo remunerado</strong>
                        </h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row">

                            <div class="col-md-12">

                                <figure class="highcharts-figure">
                                    <div id="container8"></div>
                                </figure>

                            </div>

                        </div>
                    </div>

                </div>

            </section>
        </div>

    </div>
</div> -->