<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>

    <div class="content-wrapper">
        <div class="content-body">
            <section id="dashboard-analytics">
                <div class="row" id="table-small">

                    <div class="col-lg-8">
                        <div class="card">
                            <div class="card-header border-bottom p-1">
                                <div class="head-label">
                                    <h6 class="mb-0"></h6>
                                </div>
                                <div class="dt-action-buttons text-right">
                                    <div class="dt-buttons d-inline-flex">
                                        <button id="btnagregar" type="button" class="dt-button create-new btn btn-primary"><i class="fa-solid fa-layer-group"></i>&nbsp; NUEVO GRUPO </button>
                                    </div>
                                </div>
                            </div>

                            <div class="card-header">
                                <h4 class="card-title"> <i class="fa-solid fa-layer-group"></i> Lista de Grupos</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="tbgrupo" class="table table-sm">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th class="text-left">#Id</th>
                                                <th class="text-left">Nombre Grupo</th>
                                                <th class="text-center">#Estado</th>
                                                <th class="text-left">Estado</th>
                                                <th class="text-center">Editar</i></th>
                                                <th class="text-center">Ir a Formula</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->ListadoGrupo)) { ?>
                                                <?php foreach ($this->ListadoGrupo as $pd) { ?>
                                                    <tr>
                                                        <td class="text-left"><strong><?php echo $pd['v_id_grupo'] ?></strong> </td>
                                                        <td class="text-left"><strong><?php echo $pd['v_descripcion'] ?></strong> </td>
                                                        <td class="text-center"><?php echo $pd['i_estado'] ?></td>
                                                        <td class="text-left"><?php echo $pd['v_nombre_estado'] ?></td>
                                                        <td class="text-center"><a id='<?php echo $pd['v_id_grupo'] ?>' class="btn btn-info btn-sm text-white editar"><span class="fa-solid fa-marker fa-beat"><b></b></span></a></td>
                                                        <td class='text-center'>
                                                            <a id='<?php echo $pd['v_id_grupo'] ?>' <?php $variable1 =  $pd['v_id_grupo'] ?> href="<?php echo BASE_URL ?><?php echo $pd['v_url'] ?>=<?php echo urlencode($variable1) ?>" class="btn btn-<?php echo $pd['v_btn1'] ?>"><i class="fas solid fa-<?php echo $pd['v_btn1Imagen'] ?>"></i></a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>



<!-- MODAL CREAR USUARIO-->
<div class="modal fade" id="modal-agregar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header  bg-gradient-success">
                <h5 class="modal-title"><i class="fa-solid fa-layer-group"></i> &nbsp;<b id="titulomodal"></b></h5><b><span id="idtabla"></span></b>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <div id="div-load"></div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Codigo</label>
                        <input type="text" id="xid" tabindex="1" class="form-control" readonly="readonly" autocomplete="off" />
                    </div>

                    <div class="form-group col-md-12">
                        <label class="form-label font-weight-bolder">Nombre de grupo:</label>
                        <input type="text" id="xnombres" tabindex="1" class="form-control" placeholder="Ingrese nombre de grupo" autocomplete="off" />
                    </div>
                </div>

                <hr>

                <div class="row">
                    <div class="col-sm-6">
                        <button id="xbtnguardar" type="button" class="btn btn-success btn-block">
                            <i class="fas fa-save"></i>
                            <b>Guardar</b></button>
                    </div>
                    <br>
                    <br>
                    <div class="col-sm-6">
                        <button id="xbtncancelar" type="button" class="btn btn-danger btn-block">
                            <i class="fas fa-ban"></i>
                            <b>Cancelar</b></button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

 