<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>

    <div class="content-wrapper">
        <div class="content-body">
            <section id="dashboard-analytics">
                <div class="row" id="table-small">
                    <div class="col-lg-7">
                        <div class="card">
                            <div class="card-header card-primary border-bottom p-1">
                                <div class="head-label">
                                    <h4 class="card-title"> <strong><i class="fa-solid fa-list"></i></i> &nbsp;GENERAR PEDIDO EN SOLOMON</strong> </h4>
                                </div>

                                <div class="col-xl-6 col-md-12 col-12 mb-0">
                                    <div class="col-12">
                                        <br>
                                        <div class="form-group row">
                                            <div class="col-sm-3 col-form-label">
                                                <label for="email-icon"><strong>&nbsp;&nbsp;<i class="fa-solid fa-filter fa-bounce"></i>&nbsp; FILTRO</strong></label>
                                            </div>
                                            <div class="col-sm-9">
                                                <select id="estado" class="form-control mb-1">
                                                    <?php foreach ($this->PedidoEstado as $st) { ?>
                                                        <option value="<?php echo $st['i_id']; ?>"><?php echo $st['v_nombre']; ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                                <div id="div-load1"></div>
                                <div class="table-responsive">
                                    <table id="tbpedidos" class="table table-sm">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th>#Pedido</th>
                                                <th>Descripcion</th>
                                                <th>Area Solicita</th>
                                                <th>Moneda</th>
                                                <th>Fecha Pedido</th>
                                                <th>Total</th>
                                                <th><i class="fa-solid fa-percent"></i> &nbsp;Avance</th>
                                                <th class="text-center"><i class="fa-solid fa-print"> &nbsp;&nbsp; </i></th>
                                                <th>&nbsp;&nbsp;Ver</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tablita-apro">
                                            <?php if (isset($this->ListadoPedidosAprobacion)) { ?>
                                                <?php foreach ($this->ListadoPedidosAprobacion as $pd) { ?>
                                                    <tr>
                                                        <td class="text-left">
                                                            <div class="media">
                                                                <div class="avatar bg-light-success mr-0">
                                                                    <div class="avatar-content">
                                                                        <i class="fa-solid fa-truck-fast"></i>
                                                                    </div>
                                                                </div>
                                                                <div class="media-body my-auto">
                                                                    <h5 class="font-weight-bolder mb-0"> &nbsp; <?php echo $pd['nu_correla'] ?></h5>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="text-left"><strong><?php echo $pd['v_nombrepedido'] ?></strong> </td>
                                                        <td class="text-left"><strong><?php echo $pd['v_nombrearea'] ?></strong> </td>
                                                        <td class="text-left"><?php echo $pd['v_moneda'] ?></td>
                                                        <td class="text-left"><?php echo $pd['d_fecha'] ?></td>
                                                        <td class="text-left"><?php echo $pd['nu_total'] ?></td>
                                                        <td class='text-left'>
                                                            <span class="badge badge-glow badge-<?php echo $pd['v_color_porcentaje'] ?> "><?php echo $pd['f_porcentaje'] ?>%</span>
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trending-up text-success font-medium-2">
                                                                <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline>
                                                                <polyline points="17 6 23 6 23 12"></polyline>
                                                            </svg>
                                                        </td>
                                                        <td class='text-center'>
                                                            <a href="<?php echo BASE_URL ?>aprobarpedido/documentopedido/<?php echo  $pd['nu_correla'] ?>" class="btn btn-danger btn-sm bol" target="_blank" style="color:white"><i class="fas fa-file-pdf fa-beat"></i></a>
                                                        </td>
                                                        <td><a id='<?php echo $pd['nu_correla'] ?>' class="btn btn-primary btn-sm text-white revisar"><span class="fa-solid fa-eye fa-beat"><b></b></span></a></td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-5">
                        <div class="card">
                            <div class="card-header border-bottom p-1">
                                <div class="head-label">
                                    <h6 class="mb-0"></h6>
                                </div>
                            </div>
                            <div class="card-header">
                                <h4 class="card-title"> <b id="idico"></b> &nbsp; Proceso de aprobacion del pedido (<b id="nropedido"></b>) </h4>
                            </div>
                            <div id="div-load"></div>
                            <div class="card-body">
                                <ul id="idtimeline" class="timeline">
                                </ul>
                                <hr>
                                <!-- <p style="text-align:center;height:5px"><strong>APROBACION COMPLETADA(%)</strong></p> -->
                                <p style="text-align:center;height:5px" id="titulo_avance"><strong></strong></p>
                                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                </div>
                                <div id="support-tracker-chart"></div>

                                <!-- <div class="form-group row">
                                    <div class="col-sm-12">
                                        <table id="tbarchivo" class="table table-sm">
                                            <thead class="thead-dark">
                                                <tr class="text-left">
                                                    <th>#Pedido</th>
                                                    <th class="text-left">Descripcion</th>
                                                    <th class="text-center"><i class="fa-solid fa-eye"></i>&nbsp;</th>
                                                    <th class="text-center"><i class="fa-solid fa-trash-can"></i> &nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody id="tablita-coti">
                                                <tr>
                                                    <td class="text-left">1000000001</td>
                                                    <td class="text-left">1000000001_20004_20220613022843</td>
                                                    <td class="text-center"><a download="1000000001_20004_20220613022843" class="btn btn-info btn-sm" style="color:white" href="http://localhost/pedidos/tutancamon.xls"><span class="fa-solid fa-file-word"><b></b></span></a></td>
                                                    <td class="text-center"><a id="1000000001_20004_20220613022843" class="btn btn-danger btn-sm text-white delete"><span class="fa-solid fa-trash-can"><b></b></span></a></td>
                                                </tr>
                                                <tr>
                                                    <td class="text-left">1000000001</td>
                                                    <td class="text-left">1000000001_20004_20220613022844</td>
                                                    <td class="text-center"><a download="1000000001_20004_20220613022844" class="btn btn-info btn-sm" style="color:white" href="http://localhost/pedidos/tutancamon.xls"><span class="fa-solid fa-file-word"><b></b></span></a></td>
                                                    <td class="text-center"><a id="1000000001_20004_20220613022844" class="btn btn-danger btn-sm text-white delete"><span class="fa-solid fa-trash-can"><b></b></span></a></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>



<!-- MODAL AGREGAR ARCHIVOS -->
<div class="modal fade" id="modal-file" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header   bg-gradient-success " style="height:35px;">
                <h5 class="modal-title col-11 text-center"><b><i class="fa-solid fa-file fa-bounce"></i>&nbsp;&nbsp;ARCHIVOS CARGADOS</b></h5>
                <button id="close_pedido" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-sm-12">
                    <div id="div-01"></div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <table id="tbarchivo" class="table table-sm">
                                <thead class="thead-dark">
                                    <tr class="text-left">
                                        <th>#Pedido</th>
                                        <th class="text-left">Item</th>
                                        <th class="text-left">Descripcion</th>
                                        <th class="text-center"><i class="fa-solid fa-eye"></i> &nbsp;&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody id="tablita-nota">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- MODAL INSERTANDO -->
<div class="modal fade" id="modal-insert" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-warning" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-warning"><strong> <i class="fa-solid fa-spinner fa-spin-pulse"></i>&nbsp; PROCESANDO...</strong></h5>
            </div>

            <div class="modal-body">
                <p>
                    <strong>Se estan procesando los datos</strong>
                </p>
                <p>
                    <strong>Tiempo transcurrido: <b id="number"></b> segundos</strong>
                </p>
            </div>
        </div>
    </div>
</div>




<!-- MODAL AGREGAR ARCHIVOS -->
<div class="modal fade" id="modal-cotizacion" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header  bg-gradient-info" style="height:37px">
                <h4 class="modal-title col-11 text-center"><b><i class="fa-solid fa-file-lines fa-bounce"></i>&nbsp;&nbsp;COTIZACIONES</b></h4>
                <button id="close_pedido" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <b style="color:rgb(0,0,0)"><strong>#Pedido &nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;</strong> </b> <strong><label id="idpedidocotizacion" style="color:rgb(0,0,0);font-weight:bold"></label></strong>
                <hr>

                <div class="row">
                    <div class="form-group col-md-9">
                        <label class="form-label font-weight-bolder" style="color:#CCB906;font-weight:bold">Seleccionar Proveedor</label>
                        <select id="xproveedor" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboLocal as $local) { ?>
                                <option value="<?php echo $local['v_id_local']; ?>"><?php echo $local['v_local']; ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <br>
                            <br>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="customCheck1" />
                                <label class="custom-control-label" for="customCheck1"><b>Proveedor Final</b></label>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>
                <div class="row">
                    <div class="col-12">
                        <div class="form-group mb-2">
                            <label for="notas" class="form-label font-weight-bold" style="color:#CCB906;font-weight:bold"><strong>Descripcion para el archivo</strong> </label>
                            <input type="text" id="descripcionfile" tabindex="1" placeholder="Ingrese descripcion" class="form-control" autocomplete="off" />
                        </div>
                    </div>
                </div>

                <label class="form-label font-weight-bold" style="color:#62BB3E;font-weight:bold"> <strong>Seleccionar Archivo </strong> </label>
                <div class="row">
                    <div class="col-sm-9">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group">
                                    <input id="archivo" name="archivo" type="file">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <button type="button" id="btnsubirfile" name="btnsubirfile" class="btn btn-danger btn-block"><b><i class="fa-solid fa-upload fa-beat"></i></b>&nbsp;&nbsp;Subir Archivo</button>
                        </div>
                    </div>
                </div>
                <br>
                <p style="text-align:center;height:5px;color:rgb(0,0,0)"><strong>Detalle de archivos cargados</strong></p>
                <hr>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <table id="tbcotizacion" class="table table-sm">
                            <thead class="thead-dark">
                                <tr class="text-left">
                                    <th>#Pedido</th>
                                    <th>#Proveedor</th>
                                    <th class="text-left">Descripcion</th>
                                    <th class="text-left">Nombre Archivo</th>
                                    <th class="text-center"><i class="fa-solid fa-eye"></i>&nbsp;</th>
                                    <th class="text-center"><i class="fa-solid fa-trash-can"></i> &nbsp;</th>
                                </tr>
                            </thead>
                            <tbody id="tablita-coti">
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>