<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-body">

            <section id="dashboard-analytics">
                <div class="row" id="table-small">
                    <div class="col-lg-7">
                        <div class="card">
                            <div class="card-header card-primary border-bottom p-1">
                                <div class="head-label">
                                    <h4 class="card-title"> <strong><i class="fa-solid fa-list"></i></i> &nbsp;FASES DE APROBACIONES</strong> </h4>
                                </div>

                                <div class="col-xl-6 col-md-12 col-12 mb-0">
                                    <div class="col-12">
                                        <br>
                                        <div class="form-group row">
                                            <div class="col-sm-3 col-form-label">
                                                <label for="email-icon"><strong>&nbsp;&nbsp;<i class="fa-solid fa-filter fa-bounce"></i>&nbsp; FILTRO</strong></label>
                                            </div>
                                            <div class="col-sm-9">
                                                <select id="estado" class="form-control mb-1">
                                                    <?php foreach ($this->PedidoEstado as $st) { ?>
                                                        <option value="<?php echo $st['i_id']; ?>"><?php echo $st['v_nombre']; ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                                <div id="div-load1"></div>

                                <div class="table-responsive">
                                    <table id="tbpedidos" class="table table-sm">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th>#Pedido</th>
                                                <th>Descripcion</th>
                                                <th>Area Solicita</th>
                                                <th>Moneda</th>
                                                <th>Fecha Pedido</th>
                                                <th>Total</th>
                                                <th><i class="fa-solid fa-percent"></i> Avance</th>
                                                <th class="text-center"><i class="fa-solid fa-print"> &nbsp;&nbsp; </i></th>
                                                <th>&nbsp;&nbsp;Ver</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tablita-apro">
                                            <?php if (isset($this->ListadoPedidosAprobacion)) { ?>
                                                <?php foreach ($this->ListadoPedidosAprobacion as $pd) { ?>
                                                    <tr>
                                                        <td class="text-left">
                                                            <div class="media">
                                                                <div class="avatar bg-light-success mr-0">
                                                                    <div class="avatar-content">
                                                                        <i class="fa-solid fa-truck-fast"></i>
                                                                    </div>
                                                                </div>
                                                                <div class="media-body my-auto">
                                                                    <h6 class="font-weight-bolder mb-0"><?php echo $pd['nu_correla'] ?></h6>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="text-left"><strong><?php echo $pd['v_nombrepedido'] ?></strong> </td>
                                                        <td class="text-left"><?php echo $pd['v_nombrearea'] ?></td>
                                                        <td class="text-left"><?php echo $pd['v_moneda'] ?></td>
                                                        <td class="text-left"><?php echo $pd['d_fecha'] ?></td>
                                                        <td class="text-left"><?php echo $pd['nu_total'] ?></td>


                                                        <td class='text-left'>
                                                            <span class="badge badge-glow badge-<?php echo $pd['v_color_porcentaje'] ?> "><?php echo $pd['f_porcentaje'] ?>%</span>
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trending-up text-success font-medium-2">
                                                                <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline>
                                                                <polyline points="17 6 23 6 23 12"></polyline>
                                                            </svg>
                                                        </td>


                                                        <td class='text-center'>
                                                            <a href="<?php echo BASE_URL ?>aprobarpedido/documentopedido/<?php echo  $pd['nu_correla'] ?>" class="btn btn-danger btn-sm bol" target="_blank" style="color:white"><i class="fas fa-file-pdf fa-beat"></i></a>
                                                        </td>



                                                        <td><a id='<?php echo $pd['nu_correla'] ?>' class="btn btn-primary btn-sm text-white revisar"><span class="fa-solid fa-eye fa-beat"><b></b></span></a></td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-5">
                        <div class="card">
                            <div class="card-header border-bottom p-1">
                                <div class="head-label">
                                    <h6 class="mb-0"></h6>
                                </div>
                            </div>
                            <div class="card-header">
                                <h4 class="card-title"> <b id="idico"></b> &nbsp; Proceso de aprobacion del pedido (<b id="nropedido"></b>) </h4>
                            </div>
                            <div id="div-load"></div>
                            <div class="card-body">
                                <ul id="idtimeline" class="timeline">
                                </ul>
                                <hr>
                                <p style="text-align:center;height:5px" id = "titulo_avance"><strong></strong></p>
                                <br>

                                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                    <!-- <ol class="carousel-indicators">
                                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                    </ol>
                                    <div class="carousel-inner" role="listbox">
                                        <div class="carousel-item active">
                                            <img class="img-fluid" src="../public/dist/img/Productosss.jpg" alt="First slide" />
                                        </div>
                                        <div class="carousel-item">
                                            <img class="img-fluid" src="../public/dist/img/Inicio.jpeg" alt="Second slide" />
                                        </div>
                                        <div class="carousel-item">
                                            <img class="img-fluid" src="../public/dist/img/Productsssos.jpg" alt="Third slide" />
                                        </div>
                                    </div>
                                    <a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a> -->
                                </div>

                                <div id="circle-container"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>



<!-- MODAL AGREGAR ARCHIVOS -->
<div class="modal fade" id="modal-file" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header   bg-gradient-success " style="height:35px;">
                <h5 class="modal-title col-11 text-center"><b><i class="fa-solid fa-file fa-bounce"></i>&nbsp;&nbsp;ARCHIVOS CARGADOS</b></h5>
                <button id="close_pedido" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div id="div-01"></div>

                <table id="tbarchivo" class="table table-sm">
                    <thead class="thead-dark">
                        <tr class="text-left">
                            <th>#Pedido</th>
                            <th class="text-left">Codigo</th>
                            <th class="text-left">Descripcion</th>
                            <th class="text-center"><i class="fa-solid fa-eye"></i> &nbsp;&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody id="tablita-nota">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- MODAL MOTIVO DE RETORNO -->
<!-- <div class="modal fade text-left modal-secondary" id="modal-retorno" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel160" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="myForm" method="post">
                <div class="modal-header  bg-gradient-success">
                    <label id="descripcion" style="color:rgb(179, 27, 0)" class="form-label font-weight-bolder text-center"></label>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="col-md-12 col-12">
                    <div class="card-body">
                        <form class="form form-horizontal">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group mb-2">
                                        <label for="notas" class="form-label font-weight-bold" style="color:#B7B730;font-weight:bold"><strong>Ingresar descripcion para el archivo</strong> </label>
                                        <textarea class="form-control" rows="1" placeholder="Ingrese descripcion" id="descripcionfile"></textarea>
                                    </div>
                                </div>

                                <input type="hidden" id="codproducto">
                                <input type="hidden" id="nombreproduco">

                                <div class="col-12">
                                    <div class="form-group row">
                                        <div class="col-sm-3 col-form-label">
                                            <label for="email-icon">Cantidad</label>
                                        </div>
                                        <div class="col-sm-9">
                                            <div class="input-group input-group-merge">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fas fa-cart-arrow-down"></i></span>
                                                </div>
                                                <input type="number" id="cantidad" class="form-control" id="itemquantity" aria-describedby="itemquantity" placeholder="0" autocomplete="off" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-group row">
                                        <div class="col-sm-3 col-form-label">
                                            <label for="email-icon">Precio</label>
                                        </div>
                                        <div class="col-sm-9">
                                            <div class="input-group input-group-merge">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fas fa-coins"></i></span>
                                                </div>
                                                <input type="number" id="precio" class="form-control" id="itemquantity" aria-describedby="itemquantity" placeholder="0" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-group row">
                                        <div class="col-sm-3 col-form-label">
                                            <label for="email-icon">Total</label>
                                        </div>
                                        <div class="col-sm-9">
                                            <div class="input-group input-group-merge">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fas fa-coins"></i></span>
                                                </div>
                                                <input type="number" id="importe" style="color:rgb(0,0,0)" class="form-control" id="itemquantity" aria-describedby="itemquantity" placeholder="0" readonly="readonly" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-9 offset-sm-3">
                                    <button id="calcular" type="button" class="btn btn-relief bg-gradient-primary"><i data-feather='percent'></i> Calcular</button>
                                    <button id="insertar" type="button" class="btn btn-relief bg-gradient-success"><i data-feather='shopping-cart'></i> Agregar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div> -->


<div class="modal fade text-left" id="modal-retorno" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="myModalLabel160" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-gradient-primary">
                <h5 style="color:rgb(255,255,255)" class="modal-title"><i class="fa-solid fa-square-check"></i> RETORNAR PARA CORRECION </h5>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="alert-success  form-label font-weight-bolder">NOTA</label>
                        <div class="input-group input-group-merge">
                            <div class="input-group-prepend">
                            </div>
                            <label id="cod" class="form-label font-weight-bolder text-center"></label>
                            <h5 style="color:rgb(0,0,0)" class="modal-title">El pedido regresara un paso anterior para su correción, segun los cambios que escriba en la nota.</h5>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <label style="color:rgb(255,165,0)" class="form-label font-weight-bolder">Ingresar Motivo</label>
                        <div class="input-group input-group-merge">
                            <div class=" input-group-prepend">
                                <span class="input-group-text"><i data-feather='folder-plus'></i></span>
                            </div>
                            <textarea class="form-control" rows="1" placeholder="Ingrese descripcion" id="notadescripcion"></textarea>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="btnguardaretorno" type="button" class="btn btn-success btn-block waves-effect waves-float waves-light"><b>Retornar</b></button>
                        </div>
                        <br>
                        <br>
                        <div class="col-sm-6">
                            <button id="btncancelaretorno" type="button" class="btn btn-danger btn-block waves-effect waves-float waves-light"><b>Cancelar</b></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- MODAL PARA PROCESOS -->
<div class="modal fade" id="modal-insert" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-warning" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-warning"><strong> <i class="fa-solid fa-spinner fa-spin-pulse"></i>&nbsp; PROCESANDO...</strong></h5>
            </div>

            <div class="modal-body">
                <p>
                    <strong>Se estan procesando los datos</strong>
                </p>
                <p>
                    <strong>Tiempo transcurrido: <b id="number"></b> segundos</strong>
                </p>
            </div>
        </div>
    </div>
</div>






<style>
    #circle-container {
        width: 150px;
        height: 150px;
        margin: 50px auto;
    }
</style>