<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>

    <div class="content-wrapper">
        <div class="content-body">


            <section id="dashboard-analytics">
                <div class="row" id="table-small">
                    <div class="col-lg-7">
                        <div class="card">
                            <div class="card-header card-primary border-bottom p-1"  >
                                <div class="head-label">
                                    <h4 class="card-title"> <strong><i class="fa-solid fa-list"></i></i> &nbsp;LISTA DE PEDIDOS</strong> </h4>
                                </div>

                                <div class="col-xl-6 col-md-12 col-12 mb-0">


                                    <div class="col-12">
                                        <br>
                                        <div class="form-group row">
                                            <div class="col-sm-3 col-form-label">
                                                <label for="email-icon"><strong>&nbsp;&nbsp;<i class="fa-solid fa-filter fa-bounce"></i>&nbsp; FILTRO</strong></label>
                                            </div>
                                            <div class="col-sm-9">
                                                <select id="estado" class="form-control mb-1" >
                                                    <?php foreach ($this->PedidoEstado as $st) { ?>
                                                        <option value="<?php echo $st['i_id']; ?>"><?php echo $st['v_nombre']; ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                            <div id="div-load1"></div>

                                <div class="table-responsive">
                                    <table id="tbpedidos" class="table table-sm">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th>#Pedido</th>
                                                <th>Descripcion</th>
                                                <th>Area Solicita</th>
                                                <th>Moneda</th>
                                                <th>Fecha Pedido</th>
                                                <th>Total</th>
                                                <th><i class="fa-solid fa-percent"></i> &nbsp;</th>
                                                <th class="text-center"><i class="fa-solid fa-print"> &nbsp;&nbsp; </i></th>
                                                <th>&nbsp;&nbsp;Ver</th>
                                            </tr>
                                        </thead>
                                        <tbody id="tablita-apro">
                                            <?php if (isset($this->ListadoPedidosAprobacion)) { ?>
                                                <?php foreach ($this->ListadoPedidosAprobacion as $pd) { ?>
                                                    <tr>
                                                        <td class="text-left">
                                                            <div class="media">
                                                                <div class="avatar bg-light-success mr-0">
                                                                    <div class="avatar-content">
                                                                        <i class="fa-solid fa-truck-fast"></i>
                                                                    </div>
                                                                </div>
                                                                <div class="media-body my-auto">
                                                                    <h5 class="font-weight-bolder mb-0"> &nbsp; <?php echo $pd['nu_correla'] ?></h5>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="text-left"><strong><?php echo $pd['v_nombrepedido'] ?></strong> </td>
                                                        <td class="text-left"><strong><?php echo $pd['v_nombrearea'] ?></strong> </td>
                                                        <td class="text-left"><?php echo $pd['v_moneda'] ?></td>
                                                        <td class="text-left"><?php echo $pd['d_fecha'] ?></td>
                                                        <td class="text-left"><?php echo $pd['nu_total'] ?></td>
                                                        <td class="text-left"><?php echo $pd['f_porcentaje'] ?></td>

                                                        <td class='text-center'>
                                                            <a href="<?php echo BASE_URL ?>aprobarpedido/documentopedido/<?php echo  $pd['nu_correla'] ?>" class="btn btn-danger btn-sm bol" target="_blank" style="color:white"><i class="fas fa-file-pdf fa-beat"></i></a>
                                                        </td>



                                                        <td><a id='<?php echo $pd['nu_correla'] ?>' class="btn btn-primary btn-sm text-white revisar"><span class="fa-solid fa-eye fa-beat"><b></b></span></a></td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-5">
                        <div class="card">
                            <div class="card-header border-bottom p-1">
                                <div class="head-label">
                                    <h6 class="mb-0"></h6>
                                </div>
                            </div>
                            <div class="card-header">
                                <h4 class="card-title"> <b id="idico"></b> &nbsp; Proceso de aprobacion del pedido (<b id="nropedido"></b>) </h4>
                            </div>
                            <div id="div-load"></div>
                            <div class="card-body">
                                <ul id="idtimeline" class="timeline">
                                </ul>
                                <hr>
                                <p style="text-align:center;height:5px"><strong>AVANCE DE APROBACION</strong></p>
                                <div id="circle-container"></div>
                            </div>


                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>



<!-- MODAL AGREGAR ARCHIVOS -->
<div class="modal fade" id="modal-file" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header   bg-gradient-success " style="height:35px;">
                <h5 class="modal-title col-11 text-center"><b><i class="fa-solid fa-file fa-bounce"></i>&nbsp;&nbsp;ARCHIVOS CARGADOS</b></h5>
                <button id="close_pedido" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-sm-12">
                    <div id="div-01"></div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <table id="tbarchivo" class="table table-sm">
                                <thead class="thead-dark">
                                    <tr class="text-left">
                                        <th>#Pedido</th>
                                        <th class="text-left">Item</th>
                                        <th class="text-left">Descripcion</th>
                                        <th class="text-center"><i class="fa-solid fa-eye"></i> &nbsp;&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody id="tablita-nota">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
    #circle-container {
        width: 150px;
        height: 150px;
        margin: 50px auto;
    }
</style>