<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-body">


            <section id="dashboard-analytics">
                <div class="row" id="table-small">

                    <div class="col-12">
                        <div class="card">
                            <div class="card-header border-bottom p-1">
                                <div class="head-label">
                                    <h6 class="mb-0"></h6>
                                </div>
                                <div class="dt-action-buttons text-right">
                                    <div class="dt-buttons d-inline-flex">
                                        <button id="btnagregar" type="button" class="dt-button create-new btn btn-primary"><i class="fa-solid fa-user-plus fa-beat"></i>&nbsp; NUEVO USUARIO </button>
                                    </div>
                                </div>
                            </div>

                            <div class="card-header">
                                <h4 class="card-title"> <i class="fa-solid fa-list"></i></i> Lista de Usuarios</h4>
                            </div>

                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="tbusuario" class="table table-sm">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th>#Documento</th>
                                                <th>Nombres</th>
                                                <th>Apellidos</th>
                                                <th>Correo:</th>
                                                <th>Perfil</th>
                                                <th>Cargo</th>
                                                <th>Local</th>
                                                <th>Area</th>
                                                <th>Editar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->ListadoUsuario)) { ?>
                                                <?php foreach ($this->ListadoUsuario as $user) { ?>
                                                    <tr>
                                                        <td class="text-left">
                                                            <div class="media">
                                                                <div class="avatar bg-light-success mr-0">
                                                                    <div class="avatar-content">
                                                                        <i data-feather="user" stroke-width="3" class="avatar-icon"></i>
                                                                    </div>
                                                                </div>
                                                                <div class="media-body my-auto">
                                                                    <h5 class="font-weight-bolder mb-0">&nbsp; <?php echo $user['v_dni'] ?></h5>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td class="text-left"><strong><?php echo $user['v_nombres'] ?></strong> </td>
                                                        <td class="text-left"><strong><?php echo $user['v_apellidos'] ?></strong> </td>
                                                        <td class="text-left"><?php echo $user['v_correo'] ?></td>
                                                        <td class="text-left"><?php echo $user['v_nombre_perfil'] ?></td>
                                                        <td class="text-left"><?php echo $user['v_carnombre'] ?></td>
                                                        <td class="text-left"><?php echo $user['v_id_local'] ?></td>
                                                        <td class="text-left"><?php echo $user['v_nombre_area'] ?></td>
                                                        <td><a id='<?php echo $user['v_dni'] ?>' class="btn btn-info btn-sm text-white editar"><span class="fa-solid fa-marker fa-beat"><b></b></span></a></td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>

    </div>
</div>



<!-- MODAL CREAR USUARIO-->
<div class="modal fade" id="modal-agregar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><b id="titulomodal"></b></h5><b><span id="idtabla"></span></b>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="div-load"></div>
                <div class="row">


                    <section class="col-lg-3">
                        <div class="media">
                            <a class="mr-25">
                                <img src="../public/doc/perfil/default.png" class="rounded mr-50" alt="profile image" height="200" width="200" />
                            </a>
                        </div>
                    </section>

                    <section class="col-lg-9">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Dni:</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="xdni" placeholder="Ingrese dni" autocomplete="off" aria-describedby="button-addon2">
                                <div class="input-group-append" id="button-addon2">
                                    <button id="btnconsultar" class="btn btn-outline-primary waves-effect" type="button">Validar</button>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Nombres:</label>
                            <input type="text" id="xnombres" tabindex="1" class="form-control" autocomplete="off" readonly="readonly" />
                        </div>
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Apellidos:</label>
                            <input type="text" id="xapellidos" tabindex="2" class="form-control" autocomplete="off" readonly="readonly" />
                        </div>


                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Correo:</label>
                            <input type="email" id="xcorreo" placeholder="Correo" tabindex="3" class="form-control" autocomplete="off" />
                        </div>
                    </section>


                    <div class="form-group col-md-4">
                        <label class="form-label font-weight-bolder">Id Genero:</label>
                        <input type="text" id="xidgenero" class="form-control" autocomplete="off" readonly="readonly" />
                    </div>

                    <div class="form-group col-md-8">
                        <label class="form-label font-weight-bolder">Genero:</label>
                        <input type="email" id="xgenero" class="form-control" autocomplete="off" readonly="readonly" />
                    </div>


                    <div class="form-group col-md-6">
                        <label class="alert-success   form-label font-weight-bolder">Perfil</label>
                        <select id="xperfil" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboPerfil as $pf) { ?>
                                <option value="<?php echo $pf['i_id']; ?>"><?php echo $pf['v_nombre']; ?></option>
                            <?php } ?>
                        </select>
                    </div>


                    <div class="form-group col-md-6">
                        <label class="alert-success   form-label font-weight-bolder">Cargo</label>
                        <select id="xcargo" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboCargo as $cg) { ?>
                                <option value="<?php echo $cg['v_carid']; ?>"><?php echo $cg['v_carnombre']; ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="alert-success   form-label font-weight-bolder">Area</label>
                        <select id="xarea" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboArea as $ar) { ?>
                                <option value="<?php echo $ar['v_areid']; ?>"><?php echo $ar['v_nombre']; ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="alert-success   form-label font-weight-bolder">Local</label>
                        <select id="xlocal" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboLocal as $local) { ?>
                                <option value="<?php echo $local['v_id_local']; ?>"><?php echo $local['v_local']; ?></option>
                            <?php } ?>
                        </select>
                    </div>


                    <div class="form-group col-md-6">
                        <div class="custom-control custom-switch custom-switch-primary">
                            <p class="mb-50">Activar para cambiar la contraseña</p>
                            <input type="checkbox" class="custom-control-input" id="customSwitch10" checked />
                            <label class="custom-control-label" for="customSwitch10">
                                <span class="switch-icon-left"><i data-feather="check"></i></span>
                                <span class="switch-icon-right"><i data-feather="x"></i></span>
                            </label>
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="register-password" class="form-label font-weight-bolder">Contraseña</label>
                        <div class="input-group input-group-merge form-password-toggle">
                            <input type="password" id="xpassword" class="form-control form-control-merge" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" tabindex="4" required readonly="readonly" />
                            <div class="input-group-append">
                                <span class="input-group-text cursor-pointer"><i data-feather="eye"></i></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="xbtnguardar" type="button" class="btn btn-success btn-block">
                                <i class="fas fa-save"></i>
                                <b>Guardar</b></button>
                        </div>
                        <br>
                        <br>
                        <div class="col-sm-6">
                            <button id="xbtncancelar" type="button" class="btn btn-danger btn-block">
                                <i class="fas fa-ban"></i>
                                <b>Cancelar</b></button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>



<!-- MODAL CREAR USUARIO-->
<!-- <div class="modal fade" id="modal-editar" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><b id="titulomodal"></b></h5><b><span id="idtabla"></span></b>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <section class="col-lg-3">
                        <div class="media">
                            <a class="mr-25">
                                <img src="../public/doc/perfil/default.png" class="rounded mr-50" alt="profile image" height="200" width="200" />
                            </a>
                        </div>
                    </section>
                    <section class="col-lg-9">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Dni:</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="dni" placeholder="Ingrese dni" autocomplete="off" aria-describedby="button-addon2">
                                <div class="input-group-append" id="button-addon2">
                                    <button id="btnconsultar" class="btn btn-outline-primary waves-effect" type="button">Validar</button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Nombres:</label>
                            <input type="text" id="xnombres" tabindex="1" class="form-control" autocomplete="off" readonly="readonly" />
                        </div>
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Apellidos:</label>
                            <input type="text" id="xapellidos" tabindex="2" class="form-control" autocomplete="off" readonly="readonly" />
                        </div>
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Correo:</label>
                            <input type="email" id="xcorreo" placeholder="Correo" tabindex="3" class="form-control" autocomplete="off" />
                        </div>
                    </section>

                    <div class="form-group col-md-6">
                        <label class="alert-success   form-label font-weight-bolder">Perfil</label>
                        <select id="xperfil" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboPerfil as $pf) { ?>
                                <option value="<?php echo $pf['i_id']; ?>"><?php echo $pf['v_nombre']; ?></option>
                            <?php } ?>
                        </select>
                    </div>


                    <div class="form-group col-md-6">
                        <label class="alert-success   form-label font-weight-bolder">Cargo</label>
                        <select id="xcargo" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboCargo as $cg) { ?>
                                <option value="<?php echo $cg['v_carid']; ?>"><?php echo $cg['v_carnombre']; ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="alert-success   form-label font-weight-bolder">Area</label>
                        <select id="xarea" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboArea as $ar) { ?>
                                <option value="<?php echo $ar['v_areid']; ?>"><?php echo $ar['v_nombre']; ?></option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="alert-success   form-label font-weight-bolder">Local</label>
                        <select id="xlocal" class="select2 form-control form-control-lg">
                            <?php foreach ($this->ComboLocal as $local) { ?>
                                <option value="<?php echo $local['v_id_local']; ?>"><?php echo $local['v_local']; ?></option>
                            <?php } ?>
                        </select>
                    </div>


                    <div class="form-group col-md-12">
                        <label for="register-password" class="form-label font-weight-bolder">Contraseña</label>
                        <div class="input-group input-group-merge form-password-toggle">
                            <input type="password" id="xpassword" class="form-control form-control-merge" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" tabindex="4" required />
                            <div class="input-group-append">
                                <span class="input-group-text cursor-pointer"><i data-feather="eye"></i></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <button id="xbtnguardar" type="button" class="btn btn-success btn-block">
                                <i class="fas fa-save"></i>
                                <b>Guardar</b></button>
                        </div>
                        <br>
                        <br>
                        <div class="col-sm-6">
                            <button id="xbtncancelar" type="button" class="btn btn-danger btn-block">
                                <i class="fas fa-ban"></i>
                                <b>Cancelar</b></button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div> -->